version: '3.9'
 
services:

   
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DATABASE: auth

    ports:
      - "5432:5432"
    volumes:
      - db_data_portfolio:/var/lib/posgressql
      - ./db.sql:/docker-entrypoint-initdb.d/0_init.sql


volumes:
  db_data_portfolio:
   